#include "support.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "../database/mysql_handler.h" // Indispensable pour l'accès BDD

// Note: last_id n'est plus utilisé car MySQL gère l'auto-incrément

void display_support(Support s) {
    printf("ID: %d | %s | %s | %s | %s | %s\n",
           s.id_support, s.titre, s.module, s.type, s.enseignant, s.date_ajout);
}

int count_elements(Liste *l) {
    int count = 0;
    Element *temp = l->premier;
    while (temp) {
        count++;
        temp = temp->suivant;
    }
    return count;
}

// Main function called by the "Add" button
void ajouter_support_gui(Liste *l, MYSQL *conn,
                         const char *titre,
                         const char *module,
                         const char *type,
                         const char *enseignant,
                         const char *chemin) {
    Support s;

    // 1. Filling in text data
    strncpy(s.titre, titre, sizeof(s.titre)-1); s.titre[sizeof(s.titre)-1]=0;
    strncpy(s.module, module, sizeof(s.module)-1); s.module[sizeof(s.module)-1]=0;
    strncpy(s.type, type, sizeof(s.type)-1); s.type[sizeof(s.type)-1]=0;
    strncpy(s.enseignant, enseignant, sizeof(s.enseignant)-1); s.enseignant[sizeof(s.enseignant)-1]=0;
    strncpy(s.chemin_fichier, chemin, sizeof(s.chemin_fichier)-1); s.chemin_fichier[sizeof(s.chemin_fichier)-1]=0;

    // 2. Date management (SQL format YYYY-MM-DD)
    time_t t = time(NULL);
    struct tm *tm_info = localtime(&t);
    strftime(s.date_ajout, sizeof(s.date_ajout), "%Y-%m-%d", tm_info);

    // 3. Insertion into MySQL
// We pass the address of s (&s) and the connection
    if (db_insert_support(&s, conn) == 0) {
        
        // --- YOUR MODIFICATION HERE ---
// Retrieving the ID generated by MySQL's AUTO_INCREMENT
        s.id_support = (int)mysql_insert_id(conn); 
        
        // 4. Add to the list in memory (for immediate display in GTK)
        addBack(l, s);
        
        printf("Succès : Support ajouté avec l'ID MySQL %d\n", s.id_support);
    } else {
        fprintf(stderr, "Erreur : Impossible d'insérer le support dans la base.\n");
    }
}