-- CREATION DE LA BASE DE DONNEES

CREATE DATABASE IF NOT EXISTS Gestion_Support;

-- UTILISATION DE LA BASE DE DONNEES NOUVELLEMENT CREE

USE Gestion_Support;

-- CREATION DE LA TABLE Support A UTILISER 

CREATE TABLE IF NOT EXISTS Support (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR(80) NOT NULL,
    module VARCHAR(80) NOT NULL,
    types VARCHAR(80) NOT NULL,
    enseignant VARCHAR(80) NOT NULL,
    chemin VARCHAR(80) NOT NULL,
    date_ajout DATETIME DEFAULT CURRENT_TIMESTAMP
);
